services:
  niue_current:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: niue_current
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
